CREATE TABLE DEMAND_REQUEST_REQUESTED_BY_UNQ
(
    REQUESTED_BY_ID   INTEGER not null primary key,
    REQUESTED_BY_NAME VARCHAR2(255)
);

create table DEMAND_REQUEST_ROLE_UNQ
(
    ROLE_ID   INTEGER not null primary key,
    ROLE_NAME VARCHAR2(255)
);

create table DEMAND_REQUEST_TECHNOLOGY_UNQ
(
    TECHNOLOGY_ID   INTEGER not null primary key,
    TECHNOLOGY_NAME VARCHAR2(255)
);
create table DEMAND_REQUEST_UNQ
(
    REQ_ID                 LONG not null primary key,
    ACTUAL_JOINING_DATE    DATE,
    COMMENTS               VARCHAR2(400),
    DOJ_OFFER_LETTER       DATE,
    DEMAND_LEVEL           VARCHAR2(255),
    OFFER_SLA_MET          VARCHAR2(255),
    OFFERED_DATE           DATE,
    OPERATING_UNIT         VARCHAR2(40),
    PRIORITY               VARCHAR2(255),
    REF_COMM_NO            VARCHAR2(15),
    REMARKS                VARCHAR2(400),
    REQUEST_TO_JOINING     INTEGER,
    REQUEST_TO_OFFER       INTEGER,
    REQUESTED_BY           VARCHAR2(255),
    REQUESTED_DATE         DATE,
    REQUESTING_TM          VARCHAR2(40),
    RESOURCE_NAME          VARCHAR2(40),
    RESOURCE_TYPE          VARCHAR2(255),
    RESPONSIBLE_TM         VARCHAR2(40),
    ROLE                   VARCHAR2(255),
    STATUS                 VARCHAR2(255),
    TARGET_DATE            DATE,
    TECHNOLOGY             VARCHAR2(255),
    COMMUNICATION_TO_MANDO VARCHAR2(255),
    HIRE_LOSS              INTEGER
);



CREATE TABLE ALL_SEQUENCES
(
    SEQUENCE_OWNER VARCHAR2(30) NOT NULL,
    SEQUENCE_NAME  VARCHAR2(30) NOT NULL,
    MIN_VALUE      NUMBER,
    MAX_VALUE      NUMBER,
    INCREMENT_BY   NUMBER       NOT NULL,
    CYCLE_FLAG     VARCHAR2(1),
    ORDER_FLAG     VARCHAR2(1),
    CACHE_SIZE     NUMBER       NOT NULL,
    LAST_NUMBER    NUMBER       NOT NULL
);